[package]
name = "zapret-wintonixos-tool"
version = "1.0.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13.2", features = ["blocking"] }
nix = { version = "0.31.1", features = ["user"]}
